server:
  port: 8098

spring:
  application:
    name: meeting-with-friends-bot
  config:
    import: classpath:application-secrets.yml
  main:
    banner-mode: off
  datasource:
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      auto-commit: false
  jpa:
    show-sql: ${SHOW_SQL}
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: ${POSTGRES_SCHEMA}
    open-in-view: false

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

weather:
  open-weather-url-part-one: ${OPEN_WEATHER_PART_ONE}
  open-weather-url-part-two: ${OPEN_WEATHER_PART_TWO}