package by.st.meetingwithfriendsbot.model.enums;

public enum CallbackType {
    MEETING_CHOOSE,
    CATEGORY_CHOOSE,
    FRIEND_INVITE,
    MEETING_CONFIRM,
    MEETING_CANCEL,
    MEETING_POSTPONE,
    FAQ_CATEGORY,
    FAQ_ANSWER_CHOOSE,
    VISA_NAME,
    MEETING_LOCATION,
    MEETING_PHOTO,
    MEETING_WEATHER,
    MEETING_ROUTE,
    MEETING_DISTANCE
}

